### ISSUE TITLE
Missing import for VfrError

### ISSUE THREAD

**Issue by LukasRychtecky** [landam/gdal-vfr#5]
It occures when forget install psycopg2:

Traceback (most recent call last):
  File "./vfr2pg.py", line 107, in <module>
    sys.exit(main())
  File "./vfr2pg.py", line 80, in main
    options['overwrite'])
  File "/srv/django/gdal-vfr/vfr4ogr/vfrpg.py", line 16, in **init**
    self._conn = self._opendb(self.odsn[3:])
  File "/srv/django/gdal-vfr/vfr4ogr/vfrpg.py", line 28, in _opendb
    raise VfrError(e)
NameError: global name 'VfrError' is not defined

**Comment by landam** [comment]
Applied in 80948cf39c4.
